lesson3_vdk/Controllers/VDKHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lesson3_vdk.Controllers
{
    public class VDKHomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

lesson3_vdk/Controllers/VDKStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lesson3_vdk.Controllers
{
    public class VDKStudentController : Controller
    {
        // GET: VDKStudent
        public ActionResult Index()
        {
            // du lieu tu view data 
            ViewData["msg"] = "ViewData -vuduckhoa";
            ViewData["time"] = DateTime.Now.ToString("hh:mm:ss dd/MM/yyyy tt");
            return View();
        }

        public ActionResult StudentList()
        {
            // su dung viewbag
            // luu tru gia tri don
            ViewBag.titleName = "danh sach hoc vien - vuduckhoa";

            //gia tri la 1 tap hop
            string[] names = { " duc khoa ", "vu khoa", "khoa cute" };
            ViewBag.list = names;

            // gia tri la 1 doi tuong
            var obj = new
            {
                ID=100,
                Name = "duckhoa",
                Age=45
            };
            ViewBag.student = obj;
            return View();
        }
        public ActionResult Insert()
        {
            return View("AddStudent");
        }
    }
}

lesson3_vdk/Views/VDKStudent/AddStudent.cshtml
@{
    ViewBag.Title = "AddStudent";
}

<h2>Form</h2>
@{Html.BeginForm("Insert", "VDKStudent");}
@Html.Label("ma sinh vien")
@Html.TextBox("hoten", "khoane")


@{Html.EndForm(); }
@{ 
    int[] names = { 10, 30, 21, 23, 33 };
}
@foreach (var item in names)
            {
                <li>@item</li>
            }

lesson3_vdk/Views/VDKStudent/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>phan mem quan li sinh vien</h2>
<h3>@ViewData["msg"]</h3>
<h3>bay gio la : @ViewData["time"]</h3>

lesson3_vdk/Views/VDKStudent/StudentList.cshtml
@{
    ViewBag.Title = "StudentList";
}

<h2>@ViewBag.titleName</h2>
<hr />
@foreach (var item in @ViewBag.list)
{
    <h5>@item</h5>
}
<hr />
<h2>thong tin sinh vien</h2>
@*<p>ID: @ViewBag.student.ID</p>
<p>Name: @ViewBag.student.Name</p>
<p>Age: @ViewBag.student.Age</p>*@
@ViewBag.student;
@Html.Partial("_ViewContact")