VdkK22CNT3Lesson10Db/Models/VdkAccount.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkK22CNT3Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VdkAccount
    {
        public int VdkID { get; set; }
        public string VdkUserName { get; set; }
        public string VdkPassword { get; set; }
        public string VdkFullName { get; set; }
        public string VdkEmail { get; set; }
        public string VdkPhone { get; set; }
        public Nullable<bool> VdkActive { get; set; }
    }
}

VdkK22CNT3Lesson10Db/Models/VdkModel2210900032.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdkK22CNT3Lesson10Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VdkK22CNT3Lesoon10DBEntities : DbContext
    {
        public VdkK22CNT3Lesoon10DBEntities()
            : base("name=VdkK22CNT3Lesoon10DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VdkAccount> VdkAccount { get; set; }
    }
}

VdkK22CNT3Lesson10Db/Models/VdkModel2210900032.Designer.cs
// T4 code generation is enabled for model 'D:\hoc\aspnet\VdkK22CNT3Lesson10Db\Models\VdkModel2210900032.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

VdkK22CNT3Lesson10Db/Models/VdkModel2210900032.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

VdkK22CNT3Lesson10Db/Controllers/VdkAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VdkK22CNT3Lesson10Db.Models;

namespace VdkK22CNT3Lesson10Db.Controllers
{
    public class VdkAccountsController : Controller
    {
        private VdkK22CNT3Lesoon10DBEntities db = new VdkK22CNT3Lesoon10DBEntities();

        // GET: VdkAccounts
        public async Task<ActionResult> Index()
        {
            return View(await db.VdkAccount.ToListAsync());
        }

        // GET: VdkAccounts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VdkAccount vdkAccount = await db.VdkAccount.FindAsync(id);
            if (vdkAccount == null)
            {
                return HttpNotFound();
            }
            return View(vdkAccount);
        }

        // GET: VdkAccounts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VdkAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "VdkID,VdkUserName,VdkPassword,VdkFullName,VdkEmail,VdkPhone,VdkActive")] VdkAccount vdkAccount)
        {
            if (ModelState.IsValid)
            {
                db.VdkAccount.Add(vdkAccount);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(vdkAccount);
        }

        // GET: VdkAccounts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VdkAccount vdkAccount = await db.VdkAccount.FindAsync(id);
            if (vdkAccount == null)
            {
                return HttpNotFound();
            }
            return View(vdkAccount);
        }

        // POST: VdkAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "VdkID,VdkUserName,VdkPassword,VdkFullName,VdkEmail,VdkPhone,VdkActive")] VdkAccount vdkAccount)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vdkAccount).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(vdkAccount);
        }

        // GET: VdkAccounts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VdkAccount vdkAccount = await db.VdkAccount.FindAsync(id);
            if (vdkAccount == null)
            {
                return HttpNotFound();
            }
            return View(vdkAccount);
        }

        // POST: VdkAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            VdkAccount vdkAccount = await db.VdkAccount.FindAsync(id);
            db.VdkAccount.Remove(vdkAccount);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        // login 
        public ActionResult VdkLogin()
        {
            var VdkModel = new VdkAccount();
            return View(VdkModel);
        }
        [HttpPost]
        public ActionResult VdkLogin(VdkAccount vdkAccount)
        {
            var vdkCheck = db.VdkAccount.Where(x=>x.VdkUserName.Equals(vdkAccount.VdkUserName) && x.VdkPassword.Equals(vdkAccount.VdkPassword)).FirstOrDefault();
            if (vdkCheck != null)
            {
                Session["VdkAccount"] = vdkCheck;
                return Redirect("/");
            }
            return View(vdkAccount);
        }
    }
}

VdkK22CNT3Lesson10Db/Controllers/VdkHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VdkK22CNT3Lesson10Db.Models;

namespace VdkK22CNT3Lesson10Db.Controllers
{
    public class VdkHomeController : Controller
    {
        public ActionResult VdkIndex()
        {
            // kiem du lieu session
            if (Session["VdkAccount"] !=null)
            {
                var vdkAccount = Session["VdkAccount"] as VdkAccount;
                ViewBag.FullName= vdkAccount.VdkFullName;
            }
            return View();
        }

        public ActionResult VdkAbout()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult VdkContact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VdkK22CNT3Lesson10Db/Views/Shared/_VdkLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "VdkIndex", "VdkHome", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "VdkIndex", "VdkHome", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "VdkAbout", "VdkHome", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "VdkContact", "VdkHome", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("dang nhap", "VdkLogin", "VdkAccounts", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("dang ky", "VdkRegisty", "VdkAccounts", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

VdkK22CNT3Lesson10Db/Views/VdkHome/VdkContact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

VdkK22CNT3Lesson10Db/Views/VdkHome/VdkIndex.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <h2>welcome to,@ViewBag.FullName</h2>
    </div>
</main>